- hosts: ubuntu 
  become: yes 
  tasks: 
    - name: Ensure that apache is installed 
      apt: 
        name: apache2 
        state: present
    - name: Ensure that Apache is running and will started on boot 
      service: 
        name: apache2 
        state: started 
        enabled: yes  
